module DatabaseConstants
  #credentials
  CREDENTIAL_ACCOUNTTYPE_INVITE = 11
  CREDENTIAL_ACCOUNTTYPE_FB_INVITE = 12
  CREDENTIAL_ACCOUNTTYPE_GMAIL_INVITE = 13
  CREDENTIAL_ACCOUNTTYPE_EMAIL_INVITE = 14
  CREDENTIAL_ACCOUNTTYPE_FACEBOOK = 1
  CREDENTIAL_ACCOUNTTYPE_GMAIL = 2
  CREDENTIAL_ACCOUNTTYPE_EMAIL = 3
  CREDENTIAL_ACTIVE_ACCOUNTTYPES = [CREDENTIAL_ACCOUNTTYPE_FACEBOOK, CREDENTIAL_ACCOUNTTYPE_GMAIL, CREDENTIAL_ACCOUNTTYPE_EMAIL]
  CREDENTIAL_ACTIVE_INVITE_ACCOUNTTYPES = [CREDENTIAL_ACCOUNTTYPE_FB_INVITE, CREDENTIAL_ACCOUNTTYPE_GMAIL_INVITE, CREDENTIAL_ACCOUNTTYPE_EMAIL_INVITE]
  
  #activity_feed
  ENTITY_TYPE_RECOMMENDATION = 1
  ACTIVITYFEEDS_RECIPIENTTYPE_CIRCLE = 1
  ACTIVITYFEEDS_RECIPIENTTYPE_USER = 2
  #activity_logs
  
  #bookmarks
  BOOKMARK_ENTITYTYPE_BUSINESS = 1
  
  #business_stats
  BUSINESS_STATS_ACTIONTYPE_VIEWS = 1
  BUSINESS_STATS_ACTIONTYPE_BOOKMARKED = 2
  BUSINESS_STATS_ACTIONTYPE_RECOMMENDED = 3
  
  #business_user_recommend
  BUSINESS_USER_RECOMMEND_RECOMMEND_TYPE_GIVE_RECOMMENDATION = 1
  BUSINESS_USER_RECOMMEND_RECOMMEND_TYPE_REQUEST_RECOMMENDATION = 2
  
  #business
  BUSINESS_SOURCETYPE_FRILPUSER = 1
  BUSINESS_SOURCETYPE_JUSTDIAL = 2
  BUSINESS_SOURCETYPE_GOOGLEPLACES = 3
  
  #circles
  CIRCLE_CIRCLETYPE_STARTUP = 1
  CIRCLE_CIRCLETYPE_ORGANIZATION = 2
  CIRCLE_CIRCLETYPE_OTHERS = 3
  CIRCLE_CIRCLETYPE_PRIVATE = 4
  CIRCLE_CIRCLESTATUS_NOT_YET_STARTED = 1
  CIRCLE_CIRCLESTATUS_INPROGRESS = 2
  CIRCLE_CIRCLESTATUS_COMPLETED = 3 

  # circle_categories
  CIRCLE_CIRCLECATEGORY_GENERAL = 1
  
  
  #email_trackers
  EMAILTRACKER_EMAILTYPE_INVITE = 1
  EMAILTRACKER_EMAILTYPE_REQUEST = 2
  EMAILTRACKER_EMAILTYPE_RESPONSE = 3
  EMAILTRACKER_EMAILTYPE_COMMUNITY_REQUEST = 4
  EMAILTRACKER_EMAILTYPE_EMAIL_INVITE_REQUEST = 5
  EMAILTRACKER_STATUS_SENT = 1
  EMAILTRACKER_STATUS_DELIVERED = 2
  
  #extern_auths
  EXTERNAUTH_PROVIDERTYPE_FACEBOOK = 1
  EXTERNAUTH_PROVIDERTYPE_GMAIL = 2
  
  #social_contacts
  SOCIALCONTACT_PROVIDERTYPE_FACEBOOK = 1
  SOCIALCONTACT_PROVIDERTYPE_GMAIL = 2
  SOCIALCONTACT_PROVIDERTYPE_EMAIL = 3
  SOCIALCONTACT_CONTACT_STATUS_NON_FRILP = 1
  SOCIALCONTACT_CONTACT_STATUS_FRILP_INVITED = 2
  SOCIALCONTACT_CONTACT_STATUS_FRILP = 3
  
  #source_frilp_category_maps
  SOURCEFRILPCATEGORYMAP_SOURCETYPE_FRILP = 1
  SOURCEFRILPCATEGORYMAP_SOURCETYPE_JUSTDIAL = 2
  SOURCEFRILPCATEGORYMAP_SOURCETYPE_GOOGLEPLACES = 3
  
  #user_hashes
  USERHASH_ENTITYTYPE_INVITE = 1
  USERHASH_ENTITYTYPE_REQUEST = 2
  USERHASH_ENTITYTYPE_RESPONSE = 3
  USERHASH_ENTITYTYPE_FB_INVITE = 4
  USERHASH_ENTITYTYPE_EMAIL_INVITE = 5
  USERHASH_ENTITYTYPE_COMMUNITY_REQUEST = 6
  USERHASH_STATUS_VERIFIED = 1
  USERHASH_STATUS_NOTVERIFIED = 0
  
  #user_pref_categories
  USERPREFCATEGORY_PREFTYPE_GETOPINION = 1
  
  #user_sessions
  USERSESSION_SESSIONTYPE_LOGIN = 1
  USERSESSION_SESSIONTYPE_VISITOR = 2
  
  #user_stats
  USERSTATS_ACTIONTYPE_VIEWS = 1
  USERSTATS_ACTIONTYPE_THANKS = 2
  USERSTATS_ACTIONTYPE_BUSINESS_RECOMMENDED = 3
  
  #request_recipient
  REQUEST_RECIPIENT_STATUS_SENT = 1
  REQUEST_RECIPIENT_STATUS_RESPONDED = 2 
  
  #user_activity
  USER_ACTIVITY_ENTITY_TYPE_REQUEST = 1
  USER_ACTIVITY_ENTITY_TYPE_RESPONSE = 2
  USER_ACTIVITY_ENTITY_TYPE_THANK = 3
  USER_ACTIVITY_STATUS_UNREAD = 1
  USER_ACTIVITY_STATUS_READ = 2
  USER_ACTIVITY_STATUS_RESPONDED = 3
  USER_ACTIVITY_STATUS_THANKED = 4
  
  #autosuggest
  ENTITY_TYPE_ALL = 1
  ENTITY_TYPE_BUSINESS = 2
  ENTITY_TYPE_LOCATION = 3
  ENTITY_TYPE_CATEGORY = 4
  ENTITY_TYPE_USER = 5
  ENTITY_TYPE_WORD = 6
  ENTITY_TYPE_JDBUSINESS = 7
  
  #user_locations
  USER_LOCATION_PREFERRED_LOCATION = 1
end
